### ISSUE TITLE
getConditionalCounts mapping problem 

### ISSUE THREAD

**Issue by jserigos** [Bilingual-Annotation-Task-Force/python-tagger#1]
Hey guys, I think there is an error with the getConditionalCounts function in the CharNGra script. See the output I got below; the mapping isn't right but I'm not sure why. 

> > > sent1 = "hello hello everyone"
> > > a =getConditionalCounts(sent1, 3)
> > > for key1, val in a.items():
> > > ...     print key1, ":", val
> > > ... 
> > >    : {' ': 4, 'e': 5, 'h': 2, 'l': 4, 'o': 3, 'n': 1, 'r': 1, 'v': 1, 'y': 1}
> > >  e : {' ': 5}
> > >  h : {' ': 2}
> > >  n : {' ': 1}
> > >  o : {' ': 3}
> > >  l : {' ': 4}
> > >  r : {' ': 1}
> > >  v : {' ': 1}
> > >  y : {' ': 1}

**Comment by WallyGuzman** [comment]
I think passing in sent1 causes the above behavior since Python iterates through sent1 by characters.
Specifically, line 44 "for sentence in sentences:" will give ["h", "e", "l", "l", "o", ... , "o", "n", "e"] instead of just "hello hello everyone".
However, passing [sent1] as the parameter will give the expected output, which matches the call in line 76.

**Comment by jserigos** [comment]
Oh so right! sorry about that! i didn't read the parameters carefully enough
